apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c13ypjqbl-go 
  janus-idp.io/tekton: c13ypjqbl-go
  backstage.io/kubernetes-id: c13ypjqbl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c13ypjqbl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  